### ISSUE TITLE
Redundant.

### ISSUE THREAD

**Issue by Maksym-Motornyi** [lamster2018/EmptyLeakCanary#1]
If you need to define some behavior ONLY for release build you can define the same extension function (static method of static class in Java) in different source sets. eg:
class Application {
    fun onCreate() {
         configLeakCanary()
    }
}

in release dir:

fun configLeakCanary() {
    //do nothing
}

in debug directory

fun configLeakCanary() {
    //configure leak canary as you wish
}

**Comment by lamster2018** [comment]
[](url)

**Comment by lamster2018** [comment]
good idea , and it works for me .
